### ISSUE TITLE
A better alternative found

### ISSUE THREAD

**Issue by sergio-fry** [tomvanderlee/youtube-podcaster#1]
Convert Youtube channel into audio podcasts with 1 click. Free webservice is available. With YF you can listen to your favorite Youtube channels as audio podcasts offline. Choose any podcast player you want.

https://github.com/sergio-fry/youtube-fetcher

**Comment by tomvanderlee** [comment]
Youtube-podcaster is purely ment for my own usage.
I am just releasing the source for others to help me develop or fork into their own project.

Your comment is just unrelated self promotion and adds nothing to the project. 
I would consider it spam.

**Comment by sergio-fry** [comment]
I was not able to find any way to contact you. That's why I've decided to create an Issue. Sounds like a spam, I know. 

But could you answer:

1. Do you have your app working now?
2. Do you have any issues with performance?
3. Do you have any bans from Youtube?
4. Is it possible to subscribe on a channel (not playlist) ?

I really believe, that Youtube Fetcher is better even for you to listen to Youtube content.

BTW: it is possible to create video podcasts in mp4 (without ads)

Sorry anyway
